### ISSUE TITLE
Image overlaping workshop1 slide 11

### ISSUE THREAD

**Issue by CorentinLemaitre** [Nowosad/SIGR2021#5]
In the workshop 1 slide 11 there is the plot overlapping the names output from the r chunck. I tried to set the text output from R chunck not to go out of the left column.  

I have tried with some r chunk option and CSS but did find the good one. 

![image](https://user-images.githubusercontent.com/20289907/123936986-ff35c300-d995-11eb-98c9-adb13528b916.png)

https://nowosad.github.io/SIGR2021/workshop1/workshop1_rl.html#11

**Comment by Robinlovelace** [comment]
Good catch @CorentinLemaitre, thanks for the detailed report and I agree this is not ideal! Suggested solution: print less output to allow more space for the figure on the right hand side, shouldn't need CSS interventions.

Pull Requests are welcome.

**Comment by CorentinLemaitre** [comment]
I close the issue, I have done the pull request #6. 
(I think it is the rigth process)
